language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
  allow_failures:
    - php: 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:"$SYMFONY_VERSION"; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

install:
    - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-clover clover
